# Generated by Django 4.2.7 on 2024-01-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_user_active', 'активация/деактивация пользователя'), ('view_all_users', 'просмотр всех пользователей')]},
        ),
    ]
