# Generated by Django 4.2.7 on 2024-01-04 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_remove_customer_user_customer_email_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='текст письма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='рассылка', max_length=50, verbose_name='название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала рассылки')),
                ('next_date', models.DateTimeField(blank=True, null=True, verbose_name='дата следующего отправления')),
                ('period', models.CharField(choices=[('onetime', 'один раз'), ('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], default='none', max_length=50, verbose_name='периодичность')),
                ('status', models.CharField(default='created', max_length=50, verbose_name='статус')),
                ('customers', models.ManyToManyField(to='customer.customer', verbose_name='клиенты пользователя')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('-pk',),
            },
        ),
    ]
