# Generated by Django 4.2.7 on 2023-12-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='текст письма')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='рассылка', max_length=50, verbose_name='название')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('send_date', models.DateField(default=models.DateField(auto_now_add=True, verbose_name='дата создания'), verbose_name='дата отправления')),
                ('time', models.TimeField(verbose_name='время')),
                ('period', models.CharField(choices=[('none', 'не повторять'), ('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], default='none', max_length=50, verbose_name='периодичность')),
                ('repetitions', models.SmallIntegerField(default=1, verbose_name='количество повторений')),
                ('status', models.CharField(default='created', max_length=50, verbose_name='статус')),
                ('customers', models.ManyToManyField(to='customer.customer', verbose_name='клиенты пользователя')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('-pk',),
            },
        ),
    ]
