# Generated by Django 4.2.7 on 2023-12-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='письмо'),
        ),
    ]
