# Generated by Django 4.2.7 on 2024-01-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('-pk',), 'permissions': [('set_mailing_status', 'изменение статуса рассылки'), ('view_all_mailings', 'просмотр рассылок всех пользователей')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
