# Generated by Django 4.2.7 on 2023-12-20 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_create_date_alter_mailing_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата отправления'),
        ),
    ]
