# Generated by Django 4.2.7 on 2023-12-20 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата отправления'),
        ),
    ]
