# Generated by Django 4.2.7 on 2024-01-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='user',
        ),
        migrations.AddField(
            model_name='logs',
            name='mailing_pk',
            field=models.IntegerField(default=1, verbose_name='рассылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='user_pk',
            field=models.IntegerField(default=1, verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
