# Generated by Django 4.2.7 on 2023-12-20 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 13, 27, 35, 934031, tzinfo=datetime.timezone.utc), verbose_name='дата отправления'),
        ),
    ]
