# Generated by Django 4.2.7 on 2023-12-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='письмо'),
        ),
    ]
