# Generated by Django 4.2.7 on 2023-12-23 18:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_alter_customer_first_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='user_customer_email_unique',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email', 'user')},
        ),
    ]
